# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install DuckDB CLI
        run: |
          export DUCKDB_CLI_URL=https://github.com/duckdb/duckdb/releases/download/v1.0.0/
          curl -sSL -o /tmp/duckdb.zip ${DUCKDB_CLI_URL}/duckdb_cli-linux-amd64.zip
          unzip /tmp/duckdb.zip -d /usr/local/bin/
          duckdb --version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
